config/routes.rb
if Redmine::VERSION::MAJOR >= 2
  RedmineApp::Application.routes.draw do
    resources :custom_workflows
    post '/custom_workflows/:id', :to => 'custom_workflows#update'
  end
else
  ActionController::Routing::Routes.draw do |map|
    map.resources :custom_workflows
    map.connect '/custom_workflows/:id', :controller => 'custom_workflows', :action => 'update', :conditions => { :method => :post }
  end
end

app/models/custom_workflow.rb
class WorkflowError < StandardError
  attr_accessor :error
  def initialize(message)
    @error = message.dup
    super message
  end
end

class CustomWorkflow < ActiveRecord::Base

  attr_protected :id
  has_and_belongs_to_many :projects
  acts_as_list

  validates_presence_of :name
  validates_uniqueness_of :name, :case_sensitive => false
  validate :validate_syntax

  default_scope { order(:position => :asc) }
  scope :for_all, lambda { where(:is_for_all => true) }

  def validate_syntax
    issue = Issue.new
    issue.send :instance_variable_set, :@issue, issue # compatibility with 0.0.1
    begin
      issue.instance_eval(before_save) if respond_to?(:before_save) && before_save
    rescue WorkflowError => e
    rescue Exception => e
      errors.add :before_save, :invalid_script, :error => e
    end
    begin
      issue.instance_eval(after_save) if respond_to?(:after_save) && after_save
    rescue WorkflowError => e
    rescue Exception => e
      errors.add :after_save, :invalid_script, :error => e
    end
  end

  def <=>(other)
    self.position <=> other.position
  end

  def to_s
    name
  end
end

app/controllers/custom_workflows_controller.rb
class CustomWorkflowsController < ApplicationController

  layout 'admin'
  before_filter :require_admin
  before_filter :find_workflow, :only => [:show, :edit, :update, :destroy]

  def index
    @workflows = CustomWorkflow.includes(:projects).all
    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html { redirect_to edit_custom_workflow_path }
    end
  end

  def edit
  end

  def new
    @workflow = CustomWorkflow.new
    respond_to do |format|
      format.html
    end
  end

  def create
    @workflow = CustomWorkflow.new(params[:custom_workflow])
    respond_to do |format|
      if @workflow.save
        flash[:notice] = l(:notice_successful_create)
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    respond_to do |format|
      if @workflow.update_attributes(params[:custom_workflow])
        flash[:notice] = l(:notice_successful_update)
        format.html { redirect_to(custom_workflows_path) }
      else
        format.html { render :action => :edit }
      end
    end
  end

  def destroy
    @workflow.destroy

    respond_to do |format|
      flash[:notice] = l(:notice_successful_delete)
      format.html { redirect_to(custom_workflows_path) }
    end
  end

  private

  def find_workflow
    @workflow = CustomWorkflow.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

app/views/custom_workflows/_form.html.erb
<div class="splitcontent">
  <div class="splitcontentleft box">
    <p><%= f.text_field :name, :required => true, :size => 50 %></p>

    <p><%= f.text_area :description, :cols => 40, :rows => 5 %></p>

    <p>
      <label><%= f.check_box :is_for_all, :onclick => "checkAndDisable('custom_workflow_enabled_projects', this.checked);", :no_label => true %> <%= l(:field_enabled_for_all_projects) %></label>
    </p>
  </div>

  <div class="splitcontentright">
    <fieldset class="box" id="custom_workflow_enabled_projects">
      <legend><%= l(:label_enabled_projects) %></legend>
      <%= custom_workflows_render_nested_projects(Project.visible.active) do |p|
        content_tag('label', check_box_tag('custom_workflow[project_ids][]', p.id, @workflow.project_ids.include?(p.id) || @workflow.is_for_all?,
                                           :id => nil, :disabled => @workflow.is_for_all?) + ' ' + h(p), :class => 'block')
      end %>
      <%= hidden_field_tag('custom_workflow[project_ids][]', '', :id => nil) %>
      <p><%= check_all_links 'custom_workflow_enabled_projects' %></p>
    </fieldset>
  </div>
</div>

<div style="clear: left;"></div>

<fieldset class="box">
  <legend><%= l(:label_workflow_scripts) %></legend>
  <div class="splitcontent">
    <div class="splitcontentleft">
      <%= f.text_area :before_save, :cols => 40, :rows => 20, :wrap => 'off' %>
      <em class="info"><%= l(:text_custom_workflow_before_save_note) %></em>
    </div>
    <div class="splitcontentright">
      <%= f.text_area :after_save, :cols => 40, :rows => 20, :wrap => 'off' %>
      <em class="info"><%= l(:text_custom_workflow_after_save_note) %></em>
    </div>
  </div>
  <div style="clear: left;"></div>
  <p>
    <em class="info"><%= l(:text_custom_workflow_general_note) %></em>
  </p>
</fieldset>

<script type="text/javascript">
    jQuery('#custom_workflow_before_save').taboverride(2, true);
    jQuery('#custom_workflow_after_save').taboverride(2, true);
    function checkAndDisable(id, checked) {
        if (checked) {
            jQuery('#' + id).find('input[type=checkbox]').attr('checked', true).attr('disabled', true);
        } else {
            jQuery('#' + id).find('input[type=checkbox]').removeAttr('checked').removeAttr('disabled');
        }
    }
</script>

<%= wikitoolbar_for :custom_workflow_description %>

<% content_for :header_tags do %>
    <%= javascript_include_tag "tab_override", :plugin => 'redmine_custom_workflows' %>
<% end %>

app/views/custom_workflows/edit.html.erb
<h2><%= link_to l(:label_custom_workflow_plural), custom_workflows_path %> &#187; <%= @workflow %></h2>

<%= error_messages_for 'workflow' %>

<% form = form_for @workflow, :builder => (TabularFormBuilder rescue Redmine::Views::LabelledFormBuilder) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_save) %>
<% end %>

<%= form if Redmine::VERSION::MAJOR >= 2 %>

<% html_title(l(:label_custom_workflow_plural), @workflow, l(:label_administration)) -%>

app/views/custom_workflows/index.html.erb
<% html_title(l(:label_custom_workflow_plural)) -%>
<div class="contextual">
<%= link_to l(:label_custom_workflow_new), new_custom_workflow_path, :class => 'icon icon-add' %>
</div>

<h2><%=l(:label_custom_workflow_plural)%></h2>

<div class="autoscroll">
  <% if @workflows.any? %>
  <table class="custom-workflows list">
    <thead>
    <tr>
      <th><%=l(:field_name)%></th>
      <th><%=l(:field_description)%></th>
      <th><%=l(:label_project_plural)%></th>
      <th style="width:15%;"><%= l(:button_sort) %></th>
      <th style="width:10%;"></th>
    </tr>
    </thead>
    <tbody>
    <% @workflows.each do |workflow| %>
    <tr class="<%= cycle("odd", "even") %>">
      <td class="name"><%= link_to(workflow.name, edit_custom_workflow_path(workflow)) %></td>
      <td><%= textilizable(workflow.description) %></td>
      <td align="center">
        <% if workflow.is_for_all? %>
          <%= l(:field_enabled_for_all_projects) %>
        <% elsif workflow.projects.empty? %>
          <%= l(:text_no_enabled_projects) %>
        <% else %>
          <%= workflow.projects.map(&:name).join(", ") %>
        <% end %>
      </td>
      <td align="center"><%= reorder_links("custom_workflow", {:action => 'update', :id => workflow}) %></td>
      <td class="buttons">
        <%= link_to(l(:button_delete), workflow, :class => 'icon icon-del', :data => {:confirm => l(:text_are_you_sure)}, :confirm => l(:text_are_you_sure), :method => :delete) %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
  <% else %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>

app/views/custom_workflows/new.html.erb
<h2><%= link_to l(:label_custom_workflow_plural), custom_workflows_path %> &#187; <%= l(:label_custom_workflow_new) %></h2>

<%= error_messages_for 'workflow' %>

<% form = form_for @workflow, :builder => (TabularFormBuilder rescue Redmine::Views::LabelledFormBuilder) do |f| %>
<%= render :partial => 'form', :locals => {:f => f} %>
<%= submit_tag l(:button_create) %>
<% end %>

<%= form if Redmine::VERSION::MAJOR >= 2 %>

<% html_title(l(:label_custom_workflow_plural), l(:label_custom_workflow_new), l(:label_administration)) -%>

app/views/projects/settings/_custom_workflow.html.erb
<% form = form_for @project do |f| %>
  <%= hidden_field_tag :tab, 'custom_workflow' %>
  <%= hidden_field_tag 'project[custom_workflow_ids][]', '' %>
  <fieldset>
    <legend><%= l(:text_select_project_custom_workflows) %></legend>
    <% if CustomWorkflow.exists? %>
    <dl>
      <% CustomWorkflow.all.each do |w| %>
        <dt><label><%= check_box_tag 'project[custom_workflow_ids][]', w.id, @project.custom_workflow_ids.include?(w.id) || w.is_for_all?, :disabled => w.is_for_all? %> <%= w.name %></label></dt>
        <dd><em><%= textilizable(w.description) %></em></dd>
      <% end %>
    </dl>
    <% else %>
      <p class="nodata"><%= l(:label_no_data) %></p>
    <% end %>
  </fieldset>
  <%= submit_tag l(:button_save) %>
<% end %>

<%= form if Redmine::VERSION::MAJOR >= 2 %>